const PROCESS_TYPE_DOMAIN_CHECK = 'domainCheck';
const PROCESS_TYPE_ALERT = 'alert';
const PROCESS_TYPE_HOOKS = 'hooks';

module.exports = {
  PROCESS_TYPE_DOMAIN_CHECK,
  PROCESS_TYPE_ALERT,
  PROCESS_TYPE_HOOKS,
};
